---
- name: Install nfs-utils
  yum:
    name: nfs-utils
    state: present
- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
- name: Insert into fstab mount point
  shell: |
    echo "192.168.50.10:/srv/share/ /mnt nfs vers=3,proto=udp,noauto,x-systemd.automount 0 0" >> /etc/fstab
- name: Daemon reload
  shell: "systemctl daemon-reload"
- name: Restart remotefs
  shell: "systemctl restart remote-fs.target"
...
